# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'TheMovieApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  #RxSwift
  pod 'Moya/RxSwift'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxSwiftUtilities'
  pod 'RxSwiftExt'
  
  #Dowload images
  pod 'AlamofireImage'
  
  #Animations
  pod 'lottie-ios'
  
  #Get strong typed, autocompleted resources like images, fonts and segues in Swift projects
  pod 'R.swift'

  # Pods for TheMovieApp

  target 'TheMovieAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TheMovieAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
