# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
use_frameworks!


def common_pods
    pod 'Moya/RxSwift'
    pod 'AlamofireImage'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxSwiftUtilities'
    pod 'RxSwiftExt'
    pod 'lottie-ios'
    pod 'R.swift'
end

target 'TheMovieApp' do
    inhibit_all_warnings!
    common_pods
    
    target 'TheMovieAppTests' do
        inherit! :search_paths
        inhibit_all_warnings!
        
        pod 'Nimble'
        pod 'RxBlocking'
        pod 'KIF'
        pod 'KIF/IdentifierTests'
        
        post_install do |installer|
            installer.pods_project.targets.each do |target|
                target.build_configurations.each do |config|
                    config.build_settings['ENABLE_BITCODE'] = 'YES'
                end
            end
        end
    end
end
